/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExtratoUploadRouteImport } from './routes/_authenticated/extrato/upload'
import { Route as AuthenticatedExtratoMapeamentoRouteImport } from './routes/_authenticated/extrato/mapeamento'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedExtratoOutputLayoutIndexRouteImport } from './routes/_authenticated/extrato/output-layout/index'
import { Route as AuthenticatedExtratoLotesIndexRouteImport } from './routes/_authenticated/extrato/lotes/index'
import { Route as AuthenticatedExtratoImportLayoutIndexRouteImport } from './routes/_authenticated/extrato/import-layout/index'
import { Route as AuthenticatedExtratoOutputLayoutNewRouteImport } from './routes/_authenticated/extrato/output-layout/new'
import { Route as AuthenticatedExtratoLotesIdRouteImport } from './routes/_authenticated/extrato/lotes/$id'
import { Route as AuthenticatedExtratoImportLayoutNewRouteImport } from './routes/_authenticated/extrato/import-layout/new'
import { Route as AuthenticatedExtratoOutputLayoutIdEditRouteImport } from './routes/_authenticated/extrato/output-layout/$id.edit'
import { Route as AuthenticatedExtratoImportLayoutIdEditRouteImport } from './routes/_authenticated/extrato/import-layout/$id.edit'
import { Route as AuthenticatedExtratoImportLayoutLayoutIdRulesNewRouteImport } from './routes/_authenticated/extrato/import-layout/$layoutId.rules/new'
import { Route as AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRouteImport } from './routes/_authenticated/extrato/import-layout/$layoutId.rules/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExtratoUploadRoute =
  AuthenticatedExtratoUploadRouteImport.update({
    id: '/extrato/upload',
    path: '/extrato/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoMapeamentoRoute =
  AuthenticatedExtratoMapeamentoRouteImport.update({
    id: '/extrato/mapeamento',
    path: '/extrato/mapeamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoOutputLayoutIndexRoute =
  AuthenticatedExtratoOutputLayoutIndexRouteImport.update({
    id: '/extrato/output-layout/',
    path: '/extrato/output-layout/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoLotesIndexRoute =
  AuthenticatedExtratoLotesIndexRouteImport.update({
    id: '/extrato/lotes/',
    path: '/extrato/lotes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoImportLayoutIndexRoute =
  AuthenticatedExtratoImportLayoutIndexRouteImport.update({
    id: '/extrato/import-layout/',
    path: '/extrato/import-layout/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoOutputLayoutNewRoute =
  AuthenticatedExtratoOutputLayoutNewRouteImport.update({
    id: '/extrato/output-layout/new',
    path: '/extrato/output-layout/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoLotesIdRoute =
  AuthenticatedExtratoLotesIdRouteImport.update({
    id: '/extrato/lotes/$id',
    path: '/extrato/lotes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoImportLayoutNewRoute =
  AuthenticatedExtratoImportLayoutNewRouteImport.update({
    id: '/extrato/import-layout/new',
    path: '/extrato/import-layout/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoOutputLayoutIdEditRoute =
  AuthenticatedExtratoOutputLayoutIdEditRouteImport.update({
    id: '/extrato/output-layout/$id/edit',
    path: '/extrato/output-layout/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoImportLayoutIdEditRoute =
  AuthenticatedExtratoImportLayoutIdEditRouteImport.update({
    id: '/extrato/import-layout/$id/edit',
    path: '/extrato/import-layout/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute =
  AuthenticatedExtratoImportLayoutLayoutIdRulesNewRouteImport.update({
    id: '/extrato/import-layout/$layoutId/rules/new',
    path: '/extrato/import-layout/$layoutId/rules/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute =
  AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRouteImport.update({
    id: '/extrato/import-layout/$layoutId/rules/$id/edit',
    path: '/extrato/import-layout/$layoutId/rules/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/extrato/mapeamento': typeof AuthenticatedExtratoMapeamentoRoute
  '/extrato/upload': typeof AuthenticatedExtratoUploadRoute
  '/extrato/import-layout/new': typeof AuthenticatedExtratoImportLayoutNewRoute
  '/extrato/lotes/$id': typeof AuthenticatedExtratoLotesIdRoute
  '/extrato/output-layout/new': typeof AuthenticatedExtratoOutputLayoutNewRoute
  '/extrato/import-layout/': typeof AuthenticatedExtratoImportLayoutIndexRoute
  '/extrato/lotes/': typeof AuthenticatedExtratoLotesIndexRoute
  '/extrato/output-layout/': typeof AuthenticatedExtratoOutputLayoutIndexRoute
  '/extrato/import-layout/$id/edit': typeof AuthenticatedExtratoImportLayoutIdEditRoute
  '/extrato/output-layout/$id/edit': typeof AuthenticatedExtratoOutputLayoutIdEditRoute
  '/extrato/import-layout/$layoutId/rules/new': typeof AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute
  '/extrato/import-layout/$layoutId/rules/$id/edit': typeof AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/extrato/mapeamento': typeof AuthenticatedExtratoMapeamentoRoute
  '/extrato/upload': typeof AuthenticatedExtratoUploadRoute
  '/extrato/import-layout/new': typeof AuthenticatedExtratoImportLayoutNewRoute
  '/extrato/lotes/$id': typeof AuthenticatedExtratoLotesIdRoute
  '/extrato/output-layout/new': typeof AuthenticatedExtratoOutputLayoutNewRoute
  '/extrato/import-layout': typeof AuthenticatedExtratoImportLayoutIndexRoute
  '/extrato/lotes': typeof AuthenticatedExtratoLotesIndexRoute
  '/extrato/output-layout': typeof AuthenticatedExtratoOutputLayoutIndexRoute
  '/extrato/import-layout/$id/edit': typeof AuthenticatedExtratoImportLayoutIdEditRoute
  '/extrato/output-layout/$id/edit': typeof AuthenticatedExtratoOutputLayoutIdEditRoute
  '/extrato/import-layout/$layoutId/rules/new': typeof AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute
  '/extrato/import-layout/$layoutId/rules/$id/edit': typeof AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/extrato/mapeamento': typeof AuthenticatedExtratoMapeamentoRoute
  '/_authenticated/extrato/upload': typeof AuthenticatedExtratoUploadRoute
  '/_authenticated/extrato/import-layout/new': typeof AuthenticatedExtratoImportLayoutNewRoute
  '/_authenticated/extrato/lotes/$id': typeof AuthenticatedExtratoLotesIdRoute
  '/_authenticated/extrato/output-layout/new': typeof AuthenticatedExtratoOutputLayoutNewRoute
  '/_authenticated/extrato/import-layout/': typeof AuthenticatedExtratoImportLayoutIndexRoute
  '/_authenticated/extrato/lotes/': typeof AuthenticatedExtratoLotesIndexRoute
  '/_authenticated/extrato/output-layout/': typeof AuthenticatedExtratoOutputLayoutIndexRoute
  '/_authenticated/extrato/import-layout/$id/edit': typeof AuthenticatedExtratoImportLayoutIdEditRoute
  '/_authenticated/extrato/output-layout/$id/edit': typeof AuthenticatedExtratoOutputLayoutIdEditRoute
  '/_authenticated/extrato/import-layout/$layoutId/rules/new': typeof AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute
  '/_authenticated/extrato/import-layout/$layoutId/rules/$id/edit': typeof AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/usuarios'
    | '/extrato/mapeamento'
    | '/extrato/upload'
    | '/extrato/import-layout/new'
    | '/extrato/lotes/$id'
    | '/extrato/output-layout/new'
    | '/extrato/import-layout/'
    | '/extrato/lotes/'
    | '/extrato/output-layout/'
    | '/extrato/import-layout/$id/edit'
    | '/extrato/output-layout/$id/edit'
    | '/extrato/import-layout/$layoutId/rules/new'
    | '/extrato/import-layout/$layoutId/rules/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/usuarios'
    | '/extrato/mapeamento'
    | '/extrato/upload'
    | '/extrato/import-layout/new'
    | '/extrato/lotes/$id'
    | '/extrato/output-layout/new'
    | '/extrato/import-layout'
    | '/extrato/lotes'
    | '/extrato/output-layout'
    | '/extrato/import-layout/$id/edit'
    | '/extrato/output-layout/$id/edit'
    | '/extrato/import-layout/$layoutId/rules/new'
    | '/extrato/import-layout/$layoutId/rules/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/extrato/mapeamento'
    | '/_authenticated/extrato/upload'
    | '/_authenticated/extrato/import-layout/new'
    | '/_authenticated/extrato/lotes/$id'
    | '/_authenticated/extrato/output-layout/new'
    | '/_authenticated/extrato/import-layout/'
    | '/_authenticated/extrato/lotes/'
    | '/_authenticated/extrato/output-layout/'
    | '/_authenticated/extrato/import-layout/$id/edit'
    | '/_authenticated/extrato/output-layout/$id/edit'
    | '/_authenticated/extrato/import-layout/$layoutId/rules/new'
    | '/_authenticated/extrato/import-layout/$layoutId/rules/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/upload': {
      id: '/_authenticated/extrato/upload'
      path: '/extrato/upload'
      fullPath: '/extrato/upload'
      preLoaderRoute: typeof AuthenticatedExtratoUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/mapeamento': {
      id: '/_authenticated/extrato/mapeamento'
      path: '/extrato/mapeamento'
      fullPath: '/extrato/mapeamento'
      preLoaderRoute: typeof AuthenticatedExtratoMapeamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/output-layout/': {
      id: '/_authenticated/extrato/output-layout/'
      path: '/extrato/output-layout'
      fullPath: '/extrato/output-layout/'
      preLoaderRoute: typeof AuthenticatedExtratoOutputLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/lotes/': {
      id: '/_authenticated/extrato/lotes/'
      path: '/extrato/lotes'
      fullPath: '/extrato/lotes/'
      preLoaderRoute: typeof AuthenticatedExtratoLotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/import-layout/': {
      id: '/_authenticated/extrato/import-layout/'
      path: '/extrato/import-layout'
      fullPath: '/extrato/import-layout/'
      preLoaderRoute: typeof AuthenticatedExtratoImportLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/output-layout/new': {
      id: '/_authenticated/extrato/output-layout/new'
      path: '/extrato/output-layout/new'
      fullPath: '/extrato/output-layout/new'
      preLoaderRoute: typeof AuthenticatedExtratoOutputLayoutNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/lotes/$id': {
      id: '/_authenticated/extrato/lotes/$id'
      path: '/extrato/lotes/$id'
      fullPath: '/extrato/lotes/$id'
      preLoaderRoute: typeof AuthenticatedExtratoLotesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/import-layout/new': {
      id: '/_authenticated/extrato/import-layout/new'
      path: '/extrato/import-layout/new'
      fullPath: '/extrato/import-layout/new'
      preLoaderRoute: typeof AuthenticatedExtratoImportLayoutNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/output-layout/$id/edit': {
      id: '/_authenticated/extrato/output-layout/$id/edit'
      path: '/extrato/output-layout/$id/edit'
      fullPath: '/extrato/output-layout/$id/edit'
      preLoaderRoute: typeof AuthenticatedExtratoOutputLayoutIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/import-layout/$id/edit': {
      id: '/_authenticated/extrato/import-layout/$id/edit'
      path: '/extrato/import-layout/$id/edit'
      fullPath: '/extrato/import-layout/$id/edit'
      preLoaderRoute: typeof AuthenticatedExtratoImportLayoutIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/import-layout/$layoutId/rules/new': {
      id: '/_authenticated/extrato/import-layout/$layoutId/rules/new'
      path: '/extrato/import-layout/$layoutId/rules/new'
      fullPath: '/extrato/import-layout/$layoutId/rules/new'
      preLoaderRoute: typeof AuthenticatedExtratoImportLayoutLayoutIdRulesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrato/import-layout/$layoutId/rules/$id/edit': {
      id: '/_authenticated/extrato/import-layout/$layoutId/rules/$id/edit'
      path: '/extrato/import-layout/$layoutId/rules/$id/edit'
      fullPath: '/extrato/import-layout/$layoutId/rules/$id/edit'
      preLoaderRoute: typeof AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedExtratoMapeamentoRoute: typeof AuthenticatedExtratoMapeamentoRoute
  AuthenticatedExtratoUploadRoute: typeof AuthenticatedExtratoUploadRoute
  AuthenticatedExtratoImportLayoutNewRoute: typeof AuthenticatedExtratoImportLayoutNewRoute
  AuthenticatedExtratoLotesIdRoute: typeof AuthenticatedExtratoLotesIdRoute
  AuthenticatedExtratoOutputLayoutNewRoute: typeof AuthenticatedExtratoOutputLayoutNewRoute
  AuthenticatedExtratoImportLayoutIndexRoute: typeof AuthenticatedExtratoImportLayoutIndexRoute
  AuthenticatedExtratoLotesIndexRoute: typeof AuthenticatedExtratoLotesIndexRoute
  AuthenticatedExtratoOutputLayoutIndexRoute: typeof AuthenticatedExtratoOutputLayoutIndexRoute
  AuthenticatedExtratoImportLayoutIdEditRoute: typeof AuthenticatedExtratoImportLayoutIdEditRoute
  AuthenticatedExtratoOutputLayoutIdEditRoute: typeof AuthenticatedExtratoOutputLayoutIdEditRoute
  AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute: typeof AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute
  AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute: typeof AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedExtratoMapeamentoRoute: AuthenticatedExtratoMapeamentoRoute,
  AuthenticatedExtratoUploadRoute: AuthenticatedExtratoUploadRoute,
  AuthenticatedExtratoImportLayoutNewRoute:
    AuthenticatedExtratoImportLayoutNewRoute,
  AuthenticatedExtratoLotesIdRoute: AuthenticatedExtratoLotesIdRoute,
  AuthenticatedExtratoOutputLayoutNewRoute:
    AuthenticatedExtratoOutputLayoutNewRoute,
  AuthenticatedExtratoImportLayoutIndexRoute:
    AuthenticatedExtratoImportLayoutIndexRoute,
  AuthenticatedExtratoLotesIndexRoute: AuthenticatedExtratoLotesIndexRoute,
  AuthenticatedExtratoOutputLayoutIndexRoute:
    AuthenticatedExtratoOutputLayoutIndexRoute,
  AuthenticatedExtratoImportLayoutIdEditRoute:
    AuthenticatedExtratoImportLayoutIdEditRoute,
  AuthenticatedExtratoOutputLayoutIdEditRoute:
    AuthenticatedExtratoOutputLayoutIdEditRoute,
  AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute:
    AuthenticatedExtratoImportLayoutLayoutIdRulesNewRoute,
  AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute:
    AuthenticatedExtratoImportLayoutLayoutIdRulesIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
